---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: oidc-clientsecret
  namespace: default
spec:
  encryptedData:
    clientSecret: AgBoeDF65sbOdE5PV8w206OEfGDgBULyksWzct7EabY1xYNrl2fEOJ+JmfkdK/tdDawdBeGE8T4rkEgXpuOSBgr30Go4fwSilJ0f9UcmJ4lDIR37Ij4LXGm1zYYWz0lWVn+dYbRPuSUYCTAx4Dg1A+fI2XbgxXGrvUqeGMUcpRwnZvwbxoPkoAG1z++oolAA9I84UplC7LbF6bOtu5QnX5gY/Q3102K0BGHoT/zQTcNF6z07OnSJt5yzuMsBK7GaA6tCMyMHUNBEEWYI9yjeL8s+zMeVW614PKn5Iw8B4ObTBqmOvRVNR5A5285ze6k6IpEgl7UTwzOblmFtXfADg5lvlEDCGjn5J9NwBLyvTNZ5hSIJ34x4iGOtETbdwD6+XuvI5Fm+1tRTWmqGSdMDknsUf0QUHTzjGzcH4Ds3vU7Yv8eid//8dY2Oo5ag2/h2jDOPYTS//SZmSCvClvjoywz26O4tQFFR1l1G75LHAXfnUUN7XSF4zxbX4OrpCvq8KnFJTad/8P7tejzlJ0yLUPRMG5hYVtYrezV/NBwn3aqYrgeRZGlnzB58G7AIQo9ELk/Bm/o4b7XU14ClDVKb2xZQCWSLxMNUFEWg759IOJHJDbjQl2sfiCFepQHZnOQEwe5Q1235ww2HPOwJ1gcaoB5eootUCBN4KcUzPy/tYg1ZbhqAdq+lRfzzGAPQRC+xqXmcxjL4y1kSKOevfJbHNEV/mJZWubPtS1gHgFx8dpVu8GO87MIVOOXj0iRgH/TYkkvVSXK77dUI6L1xUBCpcVWs0x67mCUPIYoXJGhpIOutJjIEiP6gt46a4UPYk/0POWFk8Oh10dqVZx9NX4HqTZJVQgFmzS4pRCHRlFtVa0UN0g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: oidc-clientsecret
      namespace: default
    type: Opaque
