---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: oidc-clientsecret
  namespace: monitoring
spec:
  encryptedData:
    clientSecret: AgBKVwFMOikpXnFCIDS8PlqmMW6n2d4kJj86YkGxcEWhE2QEyVetZSImtOZzDbr6h5PIGVaIJbul/OVU+abZZmzePaMKNvnuWHxUmXKyEj81PGHLLbSskcaBHIgzjITPT5o22j2ZC40AktsBfCySoPviGyrvCgErKgAtI5EsmDkcRWmJMZZUeHhkMWSH9FwdJdtPA0bAZzZ3BpVwlAkDYF9EOcRunsU7o68s4no1wy5Y6d2ozXa70U/xAPkLq5xdlcr7mpXHHF0Yxdj/0AjYovqJ7LduPW9zz+RTA9EPOhXWU2Em06ALsMwAUlyLCy0KYaSB4gFrzKrSOZ99798yTcmrLnbzn4vADSoJSWUCLAgxPiVfFLfGYA5n6oWbazB6fLExNPLaC1JhqLggxAPmRQmGGYV/sj0yXziNipNFiFVn6cAClK8h8svbISIQyrQYbakkUpXm/1A2JoE7nnqT4LXFvqwes2O6LeDcUbWvS6MPBl7I3ejgKY10ghj1ztH6TQkaV8ivJWBkjo+jRU0uby0I7BHxLNQFBHnL84oqyAfYpIZLjNZI7GlsvFHVNZzhoj67q6jH3aTgeQiRMT/UGu3N57J+6iotO4ra2OaojJ7LZSymyjEVG8/NhPTto2Wq8N6dGh1ZN0xv/ErNCDmG3UXaeyZcBbbV8s7MNDelcLKbWf8Rv1B1Y10dpUdkD1Vq3RUAP9p8Mu663QuLgOIb6WpwpLCPQR3IdS0wAnfGqjPykjdVO+/hvb3Rnnyje53r4sotD8/araIHLSZLwYO6z7W5caKLN6PPjBmSMMel2wK/u7ogOkAmZ4vz/SgLa+ayGx4LoKlUjs9F2t9AcZ7MU+4Wxt8drNOy1EdFAGlxjyTWHw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: oidc-clientsecret
      namespace: monitoring
    type: Opaque
