apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: identity
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - repoURL: 'https://charts.goauthentik.io'
      targetRevision: '2025.10.1'
      chart: authentik
      helm:
        releaseName: authentik
        valueFiles:
          - $values/authentik/values.yaml
    - repoURL: https://github.com/ZakDaMack/homelab
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true