apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: longhorn
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - repoURL: 'https://charts.longhorn.io'
      targetRevision: 'v1.10.1'
      chart: longhorn
      helm:
        releaseName: longhorn
        values: |
          preUpgradeChecker:
            jobEnabled: false
          defaulySettings:
            defaultDataPath: '/var/mnt/temp'
    
    - repoURL: https://github.com/ZakDaMack/homelab
      targetRevision: HEAD
      path: longhorn
          
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true