apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 80.9.2 
      helm:
        releaseName: kube-prometheus-stack
        values: |
          grafana:
            enabled: true
            ingress:
              enabled: true
              ingressClassName: traefik
              annotations:
                traefik.ingress.kubernetes.io/router.entrypoints: websecure
              hosts:
                - grafana.k8s.zakhaven.uk
              paths:
                - /
              tls:
                - secretName: ingress/zakhaven-tls
                  hosts:
                    - grafana.k8s.zakhaven.uk

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true