apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 80.9.2 
      helm:
        releaseName: kube-prometheus-stack
        values: |
          grafana:
            enabled: true
            ingress:
              enabled: true
              ingressClassName: ingress-traefik
              annotations:
                traefik.ingress.kubernetes.io/router.entrypoints: websecure
              hosts:
                - grafana.k8s.zakhaven.uk
              paths:
                - /

            grafana.ini:
              server:
                root_url: https://grafana.k8s.zakhaven.uk
                serve_from_sub_path: false

              users:
                auto_assign_org: true

              auth:
                disable_login_form: false
                oauth_auto_login: true 
                signout_redirect_url: "https://authentik.k8s.zakhaven.uk/application/o/grafana/end-session/"

              auth.generic_oauth:
                enabled: true
                name: authentik
                client_id: cuAopAbXzCKPqvJppWm10yT8vsCOz1ObMxxhNsM0
                client_secret: $__env{GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET}
                scopes: openid profile email
                auth_url:  https://authentik.k8s.zakhaven.uk/application/o/authorize/
                token_url: https://authentik.k8s.zakhaven.uk/application/o/token/
                api_url:   https://authentik.k8s.zakhaven.uk/application/o/userinfo/
                role_attribute_path: contains(groups[*], 'Admin') && 'Admin' || 'Viewer'

            envValueFrom:
              GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
                secretKeyRef:
                  name: oidc-clientsecret
                  key: clientSecret

          prometheus:
            prometheusSpec:
              retention: 30d
              retentionSize: "8GB"
              storageSpec:
                volumeClaimTemplate:
                  spec:
                    storageClassName: longhorn-test
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 10Gi

          alertmanager:
            alertmanagerSpec:
              storage:
                volumeClaimTemplate:
                  spec:
                    storageClassName: longhorn-test
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 5Gi

    - repoURL: https://github.com/ZakDaMack/homelab
      targetRevision: HEAD
      path: monitoring

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
    automated:
      prune: true
      selfHeal: true