---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: paperless-oidc-secret
  namespace: default
spec:
  encryptedData:
    provider: AgBnnGqS5XuiXsKHmunCfj0w4DvZswvLzZXM/TUgCyPZg99jMG44XroR3OIdMVD0q9oGZpa3NQhhLsOHbCCOWVVxLixsPpbRoFtPgQ+OxvXNCwGvyXqTzewAfA/QItPSWUojPLoI7H5g/X/8J+N/R7dyUVVZ7PRWWsHm59lfbYmoRsk58sIBaAbK7RnLJtP9RPnaBnTYq4XwU8qLIOXCU4tPXc2tMMW515fIOLUwLAf+s8vWAES++G5NVnxFm7XiuvhzpayfREM7pEe67qLTTus4sPKnMtlAnr0bL5KShu5mAUAJFUZDxy1WNeqz5xmMH5fPrVajenyzO6cX3JiroSP+Q6ha7Sq0fb8vdjiFtigYEoM/h0Ltm+SSqNGmCnmOCxPGrg255xF0uGbIaXtSnBWeIJk6CZeWDwv6Qs+i3fkVwXkFm/8ypUhLQ/HuWYPFPaq7UVZruZ2Y7mwogguKslyNuUSu5ZlSHBxR46uV/xp40umQkx/qErZgG8NF1Y/uoN9B93KEy87qM5mcG/k0XdfN1ka70n4GzB1NMzs+1BBUCFv6wooxvxMx9DSHa32sDzCArg7Ivj2+ygPG7PCxhM7syHkyJ8yQHjvB02jk2nP6JFEOLadU8eavDio/SpSnwFOsWlgP0ttYV1qenJpeK229zZDR+80AES6ky8hLNX4NsA4DOmu9p3SHav4KITTdCg2nHCamLnxfKyIvHEO3PJd+cSRH+Qk4Edq1R2lRKgH7mWo9TDWqPDGqxpd8zjOPk1RhqfVnFyxR+61IEMrzp3U4b3jLycXtIzxHkTxuoFmgz4QkPg9uqAVgkmMAuIC5s9w/MxKaz8xuO4alhimOiUxSroijnGz2FP/gIppEjmMQZEG0Z2rHvMlKd+NOLEEqzQT8XIEm+VxqO4rbIuDZJYWw2xq0eM+vhIVHXYdXjbE0ohb/TjuEpVpBEBPkBrejDTcK3AIfmsNW8NFagoElJYb7KOFhqaUku1ut1mZPWYFDXqSe6twX0apSDWZ6XAiLgiorrB0p0vkIqFyAu9b9PNN8KL8tNVgj7QlEFkjmyQ+3/mFR+1FhIgjMjYUHVoTuRzhVABGoBnQ8BWxzqxM8lTJbuP2bF7jjY4bgfibAjiUNLW50yk4x89X8QialMYCXvD4WMxUErK3VTlEYeeFpGpPtmvg0r5waqXlC9b1C0hGm8K6NlVJEC8Czw5YwAPv3TJN7cETKVgzjvbNMhEctGMVVpTmkdqmE3LNUO0LX7h4jJDmi5KeFuBm3xoCvZHeFg8wV/UwDZlGuB80AQIY3sSTy9vCRAq701HUrgHVbWD0ty57p8sPahF60sHm4ZUyVTm+YCO6o8nMQNx4Ev2OBKOXErKm7hAWAZ8CXPmSeHy2nnsQk5PSPygqOoBiNB1E1Bw2a0KEeZ2Ge26MmixX0rmMgnyJRNc3Tjp1bzm5MePl8bkYy3nL+a84b3DyDIDBVkHBmnQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: paperless-oidc-secret
      namespace: default
    type: Opaque
