---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: paperless-oidc-secret
  namespace: default
spec:
  encryptedData:
    provider: AgCMu7Mfm3N5tXtB9eZ+I0L4+2lRN00TsUqRxeFGyy+dykQ7s2n3a6omiMohVB97cA0NGHyrYd7dhCq+tuXGtx+q0FbiKfMh12F6ykqF1Q8TodOItqx8QShFbmlsVNi7ERKYY6pjkDHTos1zRc18N2+0w7cfRLZg2qfttlGkNAIWsSkZr2cC8gGH7h/e/NMth+RNCx7aBM1xxOSBM+WAPw6yA7Da8AvCjuU4Q1ZBD+Yhc91Egw9hobZuCAEQsAX2S45btbwHlNG4YHt560+yWZYZGoiV7g51oudugUgnjogWdOuorXyxD+dYYZywDczj0xPk1TaVXfvsmk4h0HAbsWsNMyy6F4pqmTb0ShZLsV1UHH8FvP3E+tg5kv3q/fyKIZ/AO7utJlvHXpgmYn247XpSKnrHlMY6XKb41ZCk3y2Mww0QLCSNnJX9BJo2PwJOqUZl4NLR5zCXOTaprmiBYgbbgVQ5Pln0YBSb9QfpT6uExOdK+/SzVGCueND3fAuC3Mj5lq/d4TaECBccWGAbzeVpEL7Lxpm7mkrWbViu60EqaaLQYqz816WpOmVFyaD4TMABgvaVc9uL8CmlRdBlsW2NMkfBdC5CfUF1pVHX1mdX20ip0oJb25Ojcb36AHdtc4jWUBvSgBPnxX3OE5E1Yo7q4sVhZ9q906HOqqDvPPvuzDMT9zb+Cy5RM5DukSFwui6TNgAuUJTlVANPPUGzqtP6Xxujjw7sRCkiOGMrRlckBNTfyWfjNxyOCV91Df0trEl2nLt3+jC5UNJ4OAvbD1LVDgN+EYWZ0XASCcF8e/+jFU1/QwWyxNThXWhg7ulX34KVQWKvfScD9GWpUml3nxI5Q9Y2ecbftESons7ppcTnmXN1/g+N+mBTm2mHEaW7TvbWIqArU5y0kvs3olFPre2jy+e/LPq8qUlwIuvg67pKpOkLnBzQGfSrZLXprWQvsCfma2qvgpFGmcUCaFtmOiNPmv2hQCiINdYFwRtOh/11IU8zT45KAGIa9U7OMssrkAMqvcz3oGvSAz4YmgtFhqOIRPolppYosa8E3juuf4Q/iVaaSjwcInuI22VA7QqZnB6jphpc5fgBwHBcwxxRtVLO45I3xVralyZRsOOIKGIkB4Hu+K+VUw3RLDAunhv9G1ezV5jmClLorwIEYdcsMwZ7fqwWpmcR/vlMYYgTJblYPpQGeMksz7UHZ6WF57uU9gdBcnlpDY/1tLFaq/g81mZVlTKAvRIB701UnWCCie6NmueoFLFTt7xrf+ez/JvBB5lnaYuT3v7BWrjGxMdhCSOPuO52j1hWiJ9IvSET0JPGEjpz6OSdRnpCU45hxmoyK7dSCdss0IdVTcuCPdA7gb7hEKS1EX+2QbQrN9AODKnd6FOV62SK+jeCNBntkt4vwGycG9vvLcauWLouRMHRyjF/30hF7s4fm1QB/3JBsivgxsMR5iaDsOd4MlU=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: paperless-oidc-secret
      namespace: default
    type: Opaque
