---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: paperless-oidc-secret
  namespace: default
spec:
  encryptedData:
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: AgBX0x+L0lD8IHphjSeSt26kwAN6EPI9m6+eykz7376p0GX1Y0eSj6EcgMqpk7tWV/pzvOoglVNsx2MroGVOAvRTFV0nNlcKiEwsUmHH4mW/lwYNY329IZqwnETbcG9pM9AkYN8Cv17H/m3Gf85pj5VvmtUmRZ5xOp0Pd8k3BRxrEx4lAXdnfDt/XoM3B/753A3+5Pen/USI2NwajtgBVNyWf8K6GcAqAebImnYrt2bt/VQB5W1cHWQQkduX4qNSKnqNsexCJX/xpa/Yxn0AQFu8J/3MebpM3lH0azpZ+KQT4BrCn4GyAF4l8CUePP0hRtJTJgrghilVjycdrKeuDknHHJWCEY/7ioFNJ7t+yv2hJ5kbwq65E6BGTrO+qlwtnOlVQMnA5Tn/5KnwV/KETdf/UCEVSHXGUGlGA/wPp9i1AGbOn7jiasNjrm75z5pzg+Dmk7mVqI67A6EDH+Hnxda5O2Bi5x+qyDiFT9ubVGrTEwhJVKE9I0GAEl2uI84bU5KTUDfYyYNv7bkR/jIrMt3vCxkBdXerVWDiYLYY/EqYUCZKiWwqgqm+Q+oXzYLwsXO0FwowS5QF3fkO/csAHAyjprgBN52pvJJeZfno37W/47poO/cxt4rPtkPUSdHb43eH2etmUak3VtKHDpTQI7eWWgFF40yJ7LtIlGzWI8UpSwPS94GJtXfbKfuizadJaPWEQDUauLHcgVhPVnU1uRhXrkzJ+3GgQQBFbrJrLIrv6GgI/l+PtVo+9a52CF5+8diTaCTGGBXGBQmjpxxDmmcxkjJuwev0D56MFbhWXZuMTqd7w7cCWJrF3Wvxo0VvdJweEFGlEyrmk5hzaeTgvHQ8Solt0QGSp60Te4WLf9lqfu6ISkbYSEWdnbFacU4my55ZrUQ3AS60jJLQjJojgoVKOnScUx8aTqTbRfyuFrXPqYVFo5KWFCbckEfsICGQn8xF10ziSmvQSglt0QLOR6F8l8boj4x9IQLs+kyAud02l0UUtNDnqWzAfR9gvgquixZI2QfiqLJKhvnCip/k18jYiuKSZ6/ZZOV6ZzOC9yYK5pTelW16sf8vGm0FO7nCVKYc2wT7R88AYK7N6JFKwKiVMcE3KMVhQUrXH/GeIAuS+tKP6bkJK+OXhbg/Hi79c769SKPhqJ9aF6we3pSQxmEiSqs3q89Ss6W5JWFCcl4HFMMmftXJElaF09J4LwDRI2k6RzclCLvVkPizXqc7g/pEGqrOG5WC5Z2QpPJ/FHvPJKCmphxK+JlIPnj7ZT4JlirkBrHoi0yvlPs+5eN/aKD71bZjBFrK6iloHYhBaQNytqIjNaZ/vLvDYduxeSfkTmGIeyrDuACgu6WTjwaOpWhopEcGS6sKHXqtAfbKKFEfB0PuFmkT9MRDjBHty+KvIMopmhavsQq1phRWsqsnDn9/ipkxCtV3dENELdk4xRrjK3A74IzdIa54x8I=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: paperless-oidc-secret
      namespace: default
    type: Opaque
