---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: outline-secret
  namespace: default
spec:
  encryptedData:
    client_secret: AgCteSy+MAff1+7iU6fouBIA4aJjdd4r7UZwOEz7UP+rh4PMxEXzWX78vEapdKBlOVNHkZs4FVIDGFRp+DKKxor9yhdwyXJadM7BG8EsyI85ormKsMuAy86hR18qkwdxQ1ROi2W7Nn6eVLfWOKIUYwCGCpF1bwr3rkWaZ3W0aUGnYXH+m5kBX+StIg4dCFCaJGfYNHqHAyYdLfwzvJbLey3D7hmkAj8dS28ItrLN03RABD8J+JMjtmljNBV1Ii0sqslVEak5QWDMZGsJCIOJdd+jH2Aol/4ahF6H3xZQxSdaQypsNfYdy34aIZhmxv90xhLYMEi7x9z2h8+hEdgGdlsPepByOplkvurQjL9bERRI7PUNJnUiw4aFiBJrMdDtUWnPJU7L1QOzZyjm57U8ogF7bIv0e1xQg6AdyOHeSCHLrGyabf72nr8p9yJ0biN9Yf6Yfj6iNif8yX6OGNWGfThqFx/Aeymjn14UYKM9nKL6dzuUGp9qx3dwRsTYmdr2KyFenkJXHMf+p1tak8qWBtiPFX4sFfPuS89rLLGdLu+Z2ByCRTmZZlceZxF0aCO74geBToE9DDfQ28TjCjQhMIT/8Ij9WLQnJ+Rn+wxN6/SJtUrNUfkLCN9nBVA8ZR6USWLuhiCKFhI61D1iteNurX9T8s9xTcsLwchosj7XtiSGxR262ppMTvzlCIRllYHI30IBk+FaE4GITsZf6S7tlAlXU8OIncrHe5xdCQazBoeMmr/yXn3PB9me7KZr3F6yyyKy4CGBoUqeoBOUWipgbljHZGQ4C3Fvt6QNwVGYdamLnE0qP7AeFk1gi5LEzpW3paN2LVhnDSogRVMkFPngd/PsxnUjRmXENY7Wsx8KLZaI1w==
    secret_key: AgClWKZzNcoof/AKjuKbZueIF1uNV6XjYWxoHey+zohyxb6ed8ooAGBJa1G8zl2rYgDsPaHBEIPZqbCA75jJ9D90maZHrTFpdgkGTxuHqkdeG7Xx7nSfb8XJBN70NrHmMLTVgTWFsmyiqOpn14xlf5lRJNmrlnrW4lLhb2ppBgdve0OOvcZimnfcEDNO5Lw+Hg/JJYld0fA0AtqYcM0v84vGQARk08c/8M4Q5VLKpnJT1OVpEaNE7nf6CAkURrd5ZKViSdrmHkt36ZeiHT43mrf+Co6u+GRaPD9ZHNF9Mow4iRCe7MWARTaCL0u/y9auDlvdKciUZ73FO2bZHBVQF9G1cbGOnFEpXyUpYduV++2FQ/2NS8lR7xHo/GYrHd2V+A2GUGqdiI/9CUggY2MF0kIP3n75H8l0TKkUeB8VcUdHr+DPd9q1L+D/T5YeEilf3F8Pio6M3aACyhq/ciFWYTpKzogRdHkXWunpjDCOx4uODLJDlXh4CqEpYhRuVkgKp2+QRyitqSNGbB5VeJdjmZHDUH3lU8PTmVnHbH0D7B/i3XfIDQYelIqvVetZazuKMsFbLNYslUbFGIxR7wYbclZPeaodv6WN7ZHd7H6H7zURNXzTx3eVbr1deMHWSjNEbj8vurFmgnFGI6WmSIgUoCOXVfuqfFaMoFlQMxK74EDsfChR1QjIOWxsyJ0/Z+n6HF4pPz9cJ2f50SplAETkguQu4rb4vx3YMIoA2n4d+0y38AODiw2qKUwQXUzE37HAzjHCeW++FOM01oxfaq8U/UQ=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: outline-secret
      namespace: default
    type: Opaque
