---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: cloudflare-api-key-secret
  namespace: ingress
spec:
  encryptedData:
    api-key: AgAZaW8LU0d+LyvumsmgO5NbhoUsJ5PhKYKMKtC8DXNhB/P0ATHw6WqgvA/BVsACKzE+yJAjjvpDzYth7toT6RXT1m0mAhR3FQQHzUrdNp4O4IAcadZPABCTFwbvM7RV8K0CgQKIn0Vc2BsAohm6WWDxJpl9eXTtx3MUbAwy5rYATeUz3wIVLVrlq+4jt46Ky2ykE72eYv8IlJx2ucXJKflpVA6v8iKvflbajG6b4mOHoht7mnfMhUwWcAmQ39hv6gYAPZA5Xxbf3/QnDO7/EDWNqeMxtCKHgp0SqgxVK7jvpP6YdAQXW/2A698YqlvPNM4GCRFSzRtR3zvSbwwMimr2SWyxbr7LVQgmFNItNvr5Qy2tHBE/QucIvOB4esftK5qVgjeHc1CZduirR7dZxoYJwBLTEHaF6C90Ej1BAYdxnFTXtzXi0+jvLGK3BTaPv5Q1vjUZCWUIIt5fHuKK2TUEDvQbXvC5jxbsX720JJdJPgwH2dRVRzCo7Gkd+dr8T7fFpvy568F3TNEPFqAJM3eec6cgeagKwcTqGzSY0fE7B/uZYDCwIgIttpIPhoZOxKPg6F+Be7TgL1L9BfW5KpTWf1T1PMaoRCMgpONZaauPybX4ALLKqcyPWoCuGVmRTlnjeKt6oGfia2BazMZtFm4TZYz3IZvdxZYxecVCYj6x/zFfUasNGDIBKBhW01DOvsTq7NZDoHOQ2LtPx3UKyDgp//Jumc7Tu4rj6UMM7WWUVZxEqKZ+
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: cloudflare-api-key-secret
      namespace: ingress
    type: Opaque
