apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: acme

spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: z.dowsett@outlook.com
    privateKeySecretRef:
      name: acme
    solvers:
      - dns01:
          cloudflare:
            email: z.dowsett@outlook.com
            apiKeySecretRef:
              name: cloudflare-api-key-secret
              key: api-key