---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: crowdsec-secret
  namespace: ingress
spec:
  encryptedData:
    bouncer_key: AgB4Z8cd66sDUdj3ss0j+MeJ48oW3bKSMKQ8EIiFj55o74cytBbQrYXY0pKTxtk/wl4BFfK1u2RTPo5W9Vmu/n0WpY3ehfpxPWj/f08qvCshQmRw2cObPyhu7aeRHWdAhJeiaphsER677vGqx8L3WVcLgWIcYZMd1cph73ltrLEC62aZv+gDh4lxAkpbwk5cX/qpBK0MHDb9cMzU0w3cV4XawqWPFZH2l9/0h6AeYf17DwZ8o+ryRBw3+rZbiKE3bUYLTezcU+2h7JNNUAJELkB+qR+ers0PlyNV2DiIDP2RrNG+wKCuRK9pBReB0MjYv7Uj0AfOonlgYKHakGqcYqAj/fI1aYsPVJwQBOREe/u1U3Xzi3UpuTWdbwumPv5bF3fnE5DGWS6JdV4jG0FS3POYzYmpEFG69AWfSzGgr176v6QZZXivz8cv1UrhUA8a49pieUmqf6EuLm4aLnJXnsDfrp6xE3ZOT5KlBd3AalEl5+jkG9wVXmdKOUYxV1YRYHkasgFVvOvJ0qFLsAdEj4TVOrgUcqZiGdpYleeoigm7nh4En/BdmeEq58UVvwVbt9U57DLt5NfH6zc3QR+/0q+MFddfPkiSF68uK7pp02UpNhXwT9BLVFvUHEQg2rVeajKvdGbL4iLKrlxLHERr4RJjhnOxQVcDpKa9XlhpBVCdnO/bxqeVfqknHC6zpAGvhh1vIIK4e5hCVT7A7wyvlFK/RCY/tGy1
    enroll_key: AgBJwTAgokt1Xvg4Zpn7y4Y0cHSgZNvluWuSC16JAitpK+AFNrUdyGEnDOL+YR3mQ3GGdDR2n8c2rsGE6S57N5PRcKQr/MlZO9WuvANDrAxUrTiV6FStEPJuhOPWmcIhxaTpFvTBbJdkqdbvOJBMQpqoJvug/om9wFxIl8OpW4fWupTZkyG8MqsqIDgKw17IN3IHDoMJ2f3y7qwcXMV3arJUFFAx2cwJyXgtqEFVUo7glSrJmM9kxcf/EZHiP3H9CL/xCXqCTS0Z+U7AKsIUMynj0EFOHU1FMv1si8V8+MaFsDVyHPB5WY7ddO+xFz9sg69i8JPgusowqiBB3vHe6oc+HVNEa+uerVI1bBFhg5i8k2uazcA5dn+MdnTWeP/9gWnaesk97INtNyTIXwq7EkXns98nMlqHXl0+B3lE4yUcYe7a42SGTpKx2w9k6eq4l0MPnAE4zLbwMEa1/jMOMWbgu0cf3FYQuZ1W5kWaK2DYWAPqno14lP00jkiYx65mJbfpzaWRURpkC6H+P31NH4jg8YGc4m5DwRjmxllwuwsNcPw3JBvitLkWnVw6GhvN95NYuQMPksQROQUlJO2kX/Syjxf1lWMjjeEgydUaQGrN9v+Zir1V8J0GiEYWoMUi05RIvCEZjMG2+UubSxpykmQ+2YUYPt+bWbzdiVf28K4rkUuEpLCaxQsVV3fZNN9v0oEcCJBujsfii89efF0YY3LqbitOtasZ2TvK
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: crowdsec-secret
      namespace: ingress
    type: Opaque
